on:
  push:
    branches: ['*'] # 브랜치가 푸시될 때마다 작업을 실행합니다.
jobs:
  - name: deft-branch-preview
    execute:
      # 패키지를 설치합니다.
      - npm install
      # ! 레포에 알맞은 빌드 명령어를 실행하세요.
      - npm run build
      # Deft CLI를 설치합니다.
      - npm i --registry https://npm.daumkakao.io -g @kakao/deft
      # 환경변수에 레포 이름을 넣습니다. 아래에서 사이트 주소를 설정할 때 사용합니다.
      - REPO=$(echo $GIT_REPO | sed 's/.*com\///')
      # 사이트를 배포합니다. CLI 사용법은 https://deft.kakao.com/cli 참고하세요.
      - deft --token=$DEFT_TOKEN --name=${REPO}_${GIT_BRANCH} ./dist
    run-on:
      image: mdock.daumkakao.io/node:18
      resources: large
    set-proxy: [shell, npm, yarn]